#ifndef __MyProjectGUIFrame__
#define __MyProjectGUIFrame__

/**
@file
Subclass of GUIFrame, which is generated by wxFormBuilder.
*/

#include "GUIFrame.h"

/** Implementing GUIFrame */
class MyProjectGUIFrame : public GUIFrame
{
protected:
	// Handlers for GUIFrame events.
	void OnClose( wxCloseEvent& event );
	void OnQuit( wxCommandEvent& event );
	void configure( wxCommandEvent& event );
	void OnAbout( wxCommandEvent& event );
	void start_ripping( wxCommandEvent& event );
	void test_john( wxCommandEvent& event );
	void stop_testjohn( wxCommandEvent& event );
	
public:
	/** Constructor */
	MyProjectGUIFrame( wxWindow* parent );
};

#endif // __MyProjectGUIFrame__
